// GENERATED by scripts/sync-brand.ts from assets/brand/brand.json — do not hand-edit. Run: deno task sync-brand
//
// The brand as data, for surfaces that need to DISPLAY it (the /brand
// reference page) rather than just use it. Contrast ratios are measured
// against #ffffff, not estimated.
export const BRAND_PINK_RAMP = [
  { step: 50, oklch: "oklch(0.971 0.014 5)", hex: "#fef2f4", onWhite: 1.09 },
  { step: 100, oklch: "oklch(0.941 0.03 5)", hex: "#fee4e9", onWhite: 1.2 },
  { step: 200, oklch: "oklch(0.892 0.059 5)", hex: "#ffccd6", onWhite: 1.41 },
  { step: 300, oklch: "oklch(0.823 0.104 5)", hex: "#ffa9bc", onWhite: 1.8 },
  { step: 400, oklch: "oklch(0.74 0.167 5)", hex: "#ff789d", onWhite: 2.49 },
  { step: 500, oklch: "oklch(0.65 0.24 5)", hex: "#fb2b7b", onWhite: 3.66 },
  { step: 600, oklch: "oklch(0.585 0.235 5)", hex: "#e10069", onWhite: 4.77 },
  { step: 700, oklch: "oklch(0.51 0.205 5)", hex: "#bb0056", onWhite: 6.47 },
  { step: 800, oklch: "oklch(0.43 0.17 5)", hex: "#940543", onWhite: 8.89 },
  { step: 900, oklch: "oklch(0.36 0.135 5)", hex: "#710b34", onWhite: 11.67 },
  { step: 950, oklch: "oklch(0.265 0.095 5)", hex: "#47071f", onWhite: 15.93 },
] as const;

export const BRAND_ROLES = [
  {
    token: "--brand-pink",
    ref: "pink.500",
    use: "THE Mesita pink. Logo fill, primary buttons, active states.",
  },
  {
    token: "--brand-pink-text",
    ref: "pink.600",
    use: "Pink text/links at body size on white — clears AA (4.77:1). pink-500 does NOT.",
  },
  {
    token: "--brand-pink-deep",
    ref: "pink.700",
    use: "Pressed states, pink text on tinted surfaces, print.",
  },
  {
    token: "--brand-ink",
    ref: null,
    use: "Body text. Warm near-black, carries a trace of the brand hue.",
  },
] as const;

export const BRAND_GEOMETRY = {
  clearSpace: 0.35,
  minSize: {
    markPx: 16,
    horizontalPx: 56,
    horizontalComfortablePx: 80,
    stackedPx: 64,
  },
  markOpticalCenterPct: 0.559,
} as const;

export const BRAND_TYPE = {
  display: {
    family: "Fraunces",
    use: "h1-h3, the wordmark, numerals in hero positions",
  },
  body: {
    family: "Inter",
    use: "everything else",
  },
} as const;
