// GENERATED by scripts/sync-shared.ts from shared/state-vocabulary.ts — do not
// hand-edit. Edit the source and run: deno task sync-shared
// State — two boxes (Pato, 2026-08-25 · 2026-08-29).
//
//   STATES (12)   Created · Active · Listed · Enriching · Enriched ·
//                 Verified · Owned · Partnered · Mesita Pay · Mesita Credits
//                 are bools (`true` / `false`). Requested is the guest request
//                 count, 0…n — not a Yes/No. Visit Rewards (wire key
//                 `promoting`, formerly labeled Promoted) is 0 | 1 | 2. Never a
//                 projects.state. Mesita Pay / Mesita Credits are per-place
//                 acceptance intent bits (places.mesita_pay_enabled /
//                 places.credits_enabled) — operator toggles on the Partner tab
//                 (admin-web-set-place-rails); engines still gate each rail.
//
//                 OWNED joined the box with MESITA-1608: an organization holds
//                 this place. It is CONSTANT on either console list — Org
//                 Places filters on it and the pool filters on its absence —
//                 and Pato kept it anyway, so both screens render one column
//                 set and the fact goes live the day an unfiltered list
//                 exists. It is not Verified: holding an address and having
//                 PROVED you hold it are different claims.
//   INTAKE (11)   own box: 0. Seed … 10. Embedding, each a bool: called or not
//
// Repeating the row name on the chip is redundant. Enriching is the live run;
// Enriched is last-completed — they are independent. Intake just names the
// eleven functions. Create 1–5 / Enrich 1–10 stay Config sequences; they are
// not a third State ladder. Wire key `seeded` stays; the label is Created.
// Function 10 was renamed `semantic` → `embedding` (§8.4); stored blobs and
// event payloads may still say `semantic` — readers fold, never rewrite.

export type StateBoolChip = "true" | "false" | "?" | "…";

/** Chip for a binary State fact. Loading and unknown stay distinct. */
export function stateBoolChip(
  value: boolean | "unknown" | "loading" | null | undefined,
): StateBoolChip {
  if (value === "loading") return "…";
  if (value === "unknown" || value == null) return "?";
  return value ? "true" : "false";
}

/**
 * Operator Visit Rewards: 0 Zero · 1 Conservative · 2 Aggressive.
 * Engine Dominant (3) displays as 2 — the picker has three strategies.
 */
export function operatorPromotingLevel(
  raw: number | null | undefined,
): 0 | 1 | 2 {
  const n = typeof raw === "number" && Number.isFinite(raw) ? Math.trunc(raw) : 0;
  if (n <= 0) return 0;
  if (n === 1) return 1;
  return 2;
}

export function promotingLevelChip(
  raw: number | null | undefined,
): "0" | "1" | "2" {
  return String(operatorPromotingLevel(raw)) as "0" | "1" | "2";
}

/** Guest request count. Missing is "?"; the State fact is the number. */
export function requestCountFromRow(
  requestCount: unknown,
): number | "unknown" {
  if (requestCount == null || requestCount === "") return "unknown";
  const n = Number(requestCount);
  if (!Number.isFinite(n) || n < 0) return "unknown";
  return Math.trunc(n);
}

/** Chip for Requested: `0` · `1` · `12` · … or `?`. Never true/false. */
export function requestCountChip(requestCount: unknown): string {
  const n = requestCountFromRow(requestCount);
  return n === "unknown" ? "?" : String(n);
}

export const OPERATOR_PROMOTING_LABEL: Record<0 | 1 | 2, string> = {
  0: "Zero",
  1: "Conservative",
  2: "Aggressive",
};

/** Live strategy → operator 0|1|2. Dominant and custom rates display as 2. */
export function promotingLevelFromStrategy(
  live: boolean,
  strategy: string | null | undefined,
): 0 | 1 | 2 {
  if (!live) return 0;
  if (strategy === "conservative") return 1;
  return 2;
}

export const GENERAL_STATE_FACTS = [
  { key: "seeded", label: "Created" },
  { key: "active", label: "Active" },
  { key: "listed", label: "Listed" },
  { key: "requested", label: "Requested" },
  { key: "enriching", label: "Enriching" },
  { key: "enriched", label: "Enriched" },
  { key: "verified", label: "Verified" },
  { key: "owned", label: "Owned" },
  { key: "partner", label: "Partnered" },
  { key: "promoting", label: "Visit Rewards" },
  { key: "mesita_pay", label: "Mesita Pay" },
  { key: "credits", label: "Mesita Credits" },
] as const;

export type GeneralStateKey = (typeof GENERAL_STATE_FACTS)[number]["key"];

/** Facts whose FALSE is a state, not a pending debt: grey pill, never rose.
 *  Same taxonomy as the catalog's BoolCell falseTone — a free place and a
 *  place that doesn't take a not-yet-live rail are not defects. */
export const STATE_FACT_FALSE_TONE: Partial<Record<GeneralStateKey, "neutral">> = {
  partner: "neutral",
  mesita_pay: "neutral",
  credits: "neutral",
  // Unclaimed is the pool's normal condition, not a debt anyone owes, so
  // Owned joins the neutral set the day it joins the box (MESITA-1608).
  //
  // Verified deliberately stays ROSE. On the console list that once looked
  // wrong — a wall of red across places nobody holds — but the fix is that
  // the pool withholds Verified entirely and renders "?", not that the tone
  // changes. On Org Places you hold the address, so unproven ownership IS a
  // debt you can settle, which is the tone's whole meaning and the existing
  // decision the State box rests on. Same for Enriching: leaving it here
  // would restyle the single-place box for a list-only concern.
  owned: "neutral",
};

/** Acceptance bits with NO engine yet (decision: Pato gate 2026-08-29).
 *  They now have a writer (the Partner tab toggles, admin-web-set-place-rails)
 *  and a reader (the Promotion score), but the rails themselves stay staged —
 *  header chips, Global Monitor filter segments and notification meta chips
 *  OMIT these until the Mesita Pay gateway / Credits PRs lift the
 *  filters; the catalog table and the State box still show them. */
export const ENGINELESS_STATE_FACT_KEYS: readonly GeneralStateKey[] = [
  "mesita_pay",
  "credits",
];

/**
 * Facts the NOTIFICATION stamper does not write (MESITA-1608).
 *
 * `admin-web-list-notifications` puts a `stateFacts` blob on each item, and
 * the feed reads facts straight out of it. Owned is not in that blob: it is a
 * join fact (`projects.organization_id`), not something an enrichment event
 * observes, and nothing stamps it.
 *
 * Which is why this list exists rather than a `?? false` at the read site.
 * Defaulting an unwritten fact to false would have made every notification in
 * the feed claim "no organization holds this place" — a statement nobody
 * checked, on a surface whose whole job is reporting what happened. The key
 * leaves the feed's type instead, so indexing it is a compile error rather
 * than a plausible-looking lie.
 *
 * Different question from ENGINELESS above: those facts ARE stamped and
 * merely have no engine driving them yet.
 */
export const UNSTAMPED_STATE_FACT_KEYS = ["owned"] as const;

/** A general fact the notification payload actually carries. */
export type StampedStateFactKey = Exclude<
  GeneralStateKey,
  (typeof UNSTAMPED_STATE_FACT_KEYS)[number]
>;

export const INTAKE_FUNCTIONS = [
  { key: "seed", label: "Seed", n: 0 },
  { key: "pulse", label: "Pulse", n: 1 },
  { key: "details", label: "Details", n: 2 },
  { key: "serp", label: "Serp", n: 3 },
  { key: "links", label: "Links", n: 4 },
  { key: "social", label: "Social", n: 5 },
  { key: "images", label: "Images", n: 6 },
  { key: "menu", label: "Menu", n: 7 },
  { key: "reviews", label: "Reviews", n: 8 },
  { key: "description", label: "Description", n: 9 },
  { key: "embedding", label: "Embedding", n: 10 },
] as const;

export type IntakeFunctionKey = (typeof INTAKE_FUNCTIONS)[number]["key"];

export const GENERAL_STATE_COUNT = GENERAL_STATE_FACTS.length;
export const INTAKE_FUNCTION_COUNT = INTAKE_FUNCTIONS.length;

/** Operator label: `0. Seed` … `10. Embedding`. */
export function intakeFunctionLabel(n: number, label: string): string {
  return `${n}. ${label}`;
}
