// Exclusive Google Table A type → one Mesita Super Category.
// The GOOGLE side is exclusive: every Table A slug maps to exactly one
// Super, or `other` (ineligible for Mesita map / not a guest pill).
// Google families are NOT the join: Food and Drink splits across
// restaurants, bars_nightlife, and cafes_bakeries. The CATEGORY side is
// multi-parent (≤2) and lives in place-taxonomy.ts — a Google type never
// carries two supers even when the matching Mesita category does
// (movie_theater the category is culture+experiences; the Google type
// picks experiences). Verified against the live Table A reference
// (478 types) on 2026-08-29.
// Search batteries (`GOOGLE_SEARCH_TYPES`) are the includedPrimaryTypes /
// includedType slugs sent to Nearby, Autocomplete, and Text Search.

export type SuperOrOther =
  | "restaurants"
  | "bars_nightlife"
  | "cafes_bakeries"
  | "sports_fitness"
  | "wellness_beauty"
  | "experiences"
  | "culture_arts"
  | "other";

/** Guest pills: the seven Google-mapped supers plus leftover Super `undefined`. */
export type GuestSuper = Exclude<SuperOrOther, "other"> | "undefined";

export const GOOGLE_SEARCH_TYPES: Record<GuestSuper, readonly string[]> = {
  restaurants: ["restaurant"] as const,
  bars_nightlife: ["bar", "night_club"] as const,
  cafes_bakeries: ["cafe", "bakery"] as const,
  sports_fitness: ["gym", "fitness_center", "yoga_studio", "sports_club"] as const,
  wellness_beauty: ["spa", "beauty_salon", "hair_salon", "massage"] as const,
  experiences: ["tourist_attraction", "amusement_park", "bowling_alley", "park", "movie_theater"] as const,
  culture_arts: ["museum", "art_gallery", "performing_arts_theater", "concert_hall"] as const,
  // Leftover/create-path Super — not a Google kind. Empty = skip Nearby.
  undefined: [] as const,
};

export const GOOGLE_TYPE_SUPER: Readonly<Record<string, SuperOrOther>> = {
  "academic_department": "other",
  "acai_shop": "cafes_bakeries",
  "accounting": "other",
  "administrative_area_level_1": "other",
  "administrative_area_level_2": "other",
  "adventure_sports_center": "experiences",
  "afghani_restaurant": "restaurants",
  "african_restaurant": "restaurants",
  "aircraft_rental_service": "other",
  "airport": "other",
  "airstrip": "other",
  "american_restaurant": "restaurants",
  "amphitheatre": "culture_arts",
  "amusement_center": "experiences",
  "amusement_park": "experiences",
  "apartment_building": "other",
  "apartment_complex": "other",
  "aquarium": "experiences",
  "arena": "experiences",
  "argentinian_restaurant": "restaurants",
  "art_gallery": "culture_arts",
  "art_museum": "culture_arts",
  "art_studio": "culture_arts",
  "asian_fusion_restaurant": "restaurants",
  "asian_grocery_store": "other",
  "asian_restaurant": "restaurants",
  "association_or_organization": "other",
  "astrologer": "other",
  "athletic_field": "sports_fitness",
  "atm": "other",
  "auditorium": "culture_arts",
  "australian_restaurant": "restaurants",
  "austrian_restaurant": "restaurants",
  "auto_parts_store": "other",
  "bagel_shop": "cafes_bakeries",
  "bakery": "cafes_bakeries",
  "bangladeshi_restaurant": "restaurants",
  "bank": "other",
  "banquet_hall": "experiences",
  "bar": "bars_nightlife",
  "bar_and_grill": "bars_nightlife",
  "barbecue_area": "experiences",
  "barbecue_restaurant": "restaurants",
  "barber_shop": "wellness_beauty",
  "basque_restaurant": "restaurants",
  "bavarian_restaurant": "restaurants",
  "beach": "other",
  "beautician": "wellness_beauty",
  "beauty_salon": "wellness_beauty",
  "bed_and_breakfast": "other",
  "beer_garden": "bars_nightlife",
  "belgian_restaurant": "restaurants",
  "bicycle_store": "other",
  "bike_sharing_station": "other",
  "bistro": "restaurants",
  "body_art_service": "wellness_beauty",
  "book_store": "other",
  "botanical_garden": "experiences",
  "bowling_alley": "experiences",
  "brazilian_restaurant": "restaurants",
  "breakfast_restaurant": "restaurants",
  "brewery": "bars_nightlife",
  "brewpub": "bars_nightlife",
  "bridge": "other",
  "british_restaurant": "restaurants",
  "brunch_restaurant": "restaurants",
  "buddhist_temple": "other",
  "budget_japanese_inn": "other",
  "buffet_restaurant": "restaurants",
  "building_materials_store": "other",
  "burmese_restaurant": "restaurants",
  "burrito_restaurant": "restaurants",
  "bus_station": "other",
  "bus_stop": "other",
  "business_center": "other",
  "butcher_shop": "other",
  "cafe": "cafes_bakeries",
  "cafeteria": "cafes_bakeries",
  "cajun_restaurant": "restaurants",
  "cake_shop": "cafes_bakeries",
  "californian_restaurant": "restaurants",
  "cambodian_restaurant": "restaurants",
  "campground": "other",
  "camping_cabin": "other",
  "candy_store": "cafes_bakeries",
  "cantonese_restaurant": "restaurants",
  "car_dealer": "other",
  "car_rental": "other",
  "car_repair": "other",
  "car_wash": "other",
  "caribbean_restaurant": "restaurants",
  "casino": "experiences",
  "castle": "culture_arts",
  "cat_cafe": "cafes_bakeries",
  "catering_service": "other",
  "cell_phone_store": "other",
  "cemetery": "other",
  "chauffeur_service": "other",
  "chicken_restaurant": "restaurants",
  "chicken_wings_restaurant": "restaurants",
  "child_care_agency": "other",
  "childrens_camp": "experiences",
  "chilean_restaurant": "restaurants",
  "chinese_noodle_restaurant": "restaurants",
  "chinese_restaurant": "restaurants",
  "chiropractor": "other",
  "chocolate_factory": "cafes_bakeries",
  "chocolate_shop": "cafes_bakeries",
  "church": "other",
  "city_hall": "other",
  "city_park": "experiences",
  "clothing_store": "other",
  "cocktail_bar": "bars_nightlife",
  "coffee_roastery": "cafes_bakeries",
  "coffee_shop": "cafes_bakeries",
  "coffee_stand": "cafes_bakeries",
  "colombian_restaurant": "restaurants",
  "comedy_club": "bars_nightlife",
  "community_center": "experiences",
  "concert_hall": "culture_arts",
  "condominium_complex": "other",
  "confectionery": "cafes_bakeries",
  "consultant": "other",
  "convenience_store": "other",
  "convention_center": "experiences",
  "corporate_office": "other",
  "cosmetics_store": "other",
  "cottage": "other",
  "country": "other",
  "courier_service": "other",
  "courthouse": "other",
  "coworking_space": "other",
  "croatian_restaurant": "restaurants",
  "cuban_restaurant": "restaurants",
  "cultural_center": "culture_arts",
  "cultural_landmark": "culture_arts",
  "cycling_park": "experiences",
  "czech_restaurant": "restaurants",
  "dance_hall": "bars_nightlife",
  "danish_restaurant": "restaurants",
  "deli": "restaurants",
  "dental_clinic": "other",
  "dentist": "other",
  "department_store": "other",
  "dessert_restaurant": "cafes_bakeries",
  "dessert_shop": "cafes_bakeries",
  "dim_sum_restaurant": "restaurants",
  "diner": "restaurants",
  "discount_store": "other",
  "discount_supermarket": "other",
  "doctor": "other",
  "dog_cafe": "cafes_bakeries",
  "dog_park": "experiences",
  "donut_shop": "cafes_bakeries",
  "drugstore": "other",
  "dumpling_restaurant": "restaurants",
  "dutch_restaurant": "restaurants",
  "eastern_european_restaurant": "restaurants",
  "ebike_charging_station": "other",
  "educational_institution": "other",
  "electric_vehicle_charging_station": "other",
  "electrician": "other",
  "electronics_store": "other",
  "embassy": "other",
  "employment_agency": "other",
  "ethiopian_restaurant": "restaurants",
  "european_restaurant": "restaurants",
  "event_venue": "experiences",
  "extended_stay_hotel": "other",
  "falafel_restaurant": "restaurants",
  "family_restaurant": "restaurants",
  "farm": "other",
  "farmers_market": "experiences",
  "farmstay": "other",
  "fast_food_restaurant": "restaurants",
  "ferris_wheel": "experiences",
  "ferry_service": "other",
  "ferry_terminal": "other",
  "filipino_restaurant": "restaurants",
  "fine_dining_restaurant": "restaurants",
  "fire_station": "other",
  "fish_and_chips_restaurant": "restaurants",
  "fishing_charter": "experiences",
  "fishing_pier": "experiences",
  "fishing_pond": "experiences",
  "fitness_center": "sports_fitness",
  "flea_market": "experiences",
  "florist": "other",
  "fondue_restaurant": "restaurants",
  "food_court": "restaurants",
  "food_delivery": "other",
  "food_store": "other",
  "foot_care": "wellness_beauty",
  "fountain": "culture_arts",
  "french_restaurant": "restaurants",
  "funeral_home": "other",
  "furniture_store": "other",
  "fusion_restaurant": "restaurants",
  "garden": "experiences",
  "garden_center": "other",
  "gas_station": "other",
  "gastropub": "restaurants",
  "general_hospital": "other",
  "general_store": "other",
  "german_restaurant": "restaurants",
  "gift_shop": "other",
  "go_karting_venue": "experiences",
  "golf_course": "sports_fitness",
  "government_office": "other",
  "greek_restaurant": "restaurants",
  "grocery_store": "other",
  "guest_house": "other",
  "gym": "sports_fitness",
  "gyro_restaurant": "restaurants",
  "hair_care": "wellness_beauty",
  "hair_salon": "wellness_beauty",
  "halal_restaurant": "restaurants",
  "hamburger_restaurant": "restaurants",
  "hardware_store": "other",
  "hawaiian_restaurant": "restaurants",
  "health_food_store": "other",
  "heliport": "other",
  "hiking_area": "experiences",
  "hindu_temple": "other",
  "historical_landmark": "experiences",
  "historical_place": "culture_arts",
  "history_museum": "culture_arts",
  "home_goods_store": "other",
  "home_improvement_store": "other",
  "hookah_bar": "bars_nightlife",
  "hospital": "other",
  "hostel": "other",
  "hot_dog_restaurant": "restaurants",
  "hot_dog_stand": "restaurants",
  "hot_pot_restaurant": "restaurants",
  "hotel": "other",
  "housing_complex": "other",
  "hungarian_restaurant": "restaurants",
  "hypermarket": "other",
  "ice_cream_shop": "cafes_bakeries",
  "ice_skating_rink": "sports_fitness",
  "indian_restaurant": "restaurants",
  "indonesian_restaurant": "restaurants",
  "indoor_golf_course": "sports_fitness",
  "indoor_playground": "experiences",
  "inn": "other",
  "insurance_agency": "other",
  "international_airport": "other",
  "internet_cafe": "experiences",
  "irish_pub": "bars_nightlife",
  "irish_restaurant": "restaurants",
  "island": "other",
  "israeli_restaurant": "restaurants",
  "italian_restaurant": "restaurants",
  "japanese_curry_restaurant": "restaurants",
  "japanese_inn": "other",
  "japanese_izakaya_restaurant": "restaurants",
  "japanese_restaurant": "restaurants",
  "jewelry_store": "other",
  "juice_shop": "cafes_bakeries",
  "karaoke": "bars_nightlife",
  "kebab_shop": "restaurants",
  "korean_barbecue_restaurant": "restaurants",
  "korean_restaurant": "restaurants",
  "lake": "other",
  "latin_american_restaurant": "restaurants",
  "laundry": "other",
  "lawyer": "other",
  "lebanese_restaurant": "restaurants",
  "library": "other",
  "light_rail_station": "other",
  "liquor_store": "other",
  "live_music_venue": "bars_nightlife",
  "local_government_office": "other",
  "locality": "other",
  "locksmith": "other",
  "lodging": "other",
  "lounge_bar": "bars_nightlife",
  "makeup_artist": "wellness_beauty",
  "malaysian_restaurant": "restaurants",
  "manufacturer": "other",
  "marina": "experiences",
  "market": "experiences",
  "marketing_consultant": "other",
  "massage": "wellness_beauty",
  "massage_spa": "wellness_beauty",
  "meal_delivery": "restaurants",
  "meal_takeaway": "restaurants",
  "medical_center": "other",
  "medical_clinic": "other",
  "medical_lab": "other",
  "mediterranean_restaurant": "restaurants",
  "mexican_restaurant": "restaurants",
  "middle_eastern_restaurant": "restaurants",
  "miniature_golf_course": "experiences",
  "mobile_home_park": "other",
  "mongolian_barbecue_restaurant": "restaurants",
  "monument": "culture_arts",
  "moroccan_restaurant": "restaurants",
  "mosque": "other",
  "motel": "other",
  "mountain_peak": "other",
  "movie_rental": "experiences",
  "movie_theater": "experiences",
  "moving_company": "other",
  "museum": "culture_arts",
  "nail_salon": "wellness_beauty",
  "national_park": "experiences",
  "nature_preserve": "other",
  "neighborhood_police_station": "other",
  "night_club": "bars_nightlife",
  "non_profit_organization": "other",
  "noodle_shop": "restaurants",
  "north_indian_restaurant": "restaurants",
  "observation_deck": "experiences",
  "off_roading_area": "experiences",
  "opera_house": "culture_arts",
  "oyster_bar_restaurant": "restaurants",
  "paintball_center": "experiences",
  "painter": "other",
  "pakistani_restaurant": "restaurants",
  "park": "experiences",
  "park_and_ride": "other",
  "parking": "other",
  "parking_garage": "other",
  "parking_lot": "other",
  "pastry_shop": "cafes_bakeries",
  "performing_arts_theater": "culture_arts",
  "persian_restaurant": "restaurants",
  "peruvian_restaurant": "restaurants",
  "pet_boarding_service": "other",
  "pet_care": "other",
  "pet_store": "other",
  "pharmacy": "other",
  "philharmonic_hall": "culture_arts",
  "physiotherapist": "other",
  "picnic_ground": "experiences",
  "pizza_delivery": "restaurants",
  "pizza_restaurant": "restaurants",
  "planetarium": "experiences",
  "playground": "experiences",
  "plaza": "experiences",
  "plumber": "other",
  "police": "other",
  "polish_restaurant": "restaurants",
  "portuguese_restaurant": "restaurants",
  "post_office": "other",
  "postal_code": "other",
  "preschool": "other",
  "primary_school": "other",
  "private_guest_room": "other",
  "psychic": "other",
  "pub": "bars_nightlife",
  "public_bath": "other",
  "public_bathroom": "other",
  "race_course": "experiences",
  "ramen_restaurant": "restaurants",
  "ranch": "other",
  "real_estate_agency": "other",
  "research_institute": "other",
  "resort_hotel": "other",
  "rest_stop": "other",
  "restaurant": "restaurants",
  "river": "other",
  "roller_coaster": "experiences",
  "romanian_restaurant": "restaurants",
  "roofing_contractor": "other",
  "russian_restaurant": "restaurants",
  "rv_park": "other",
  "salad_shop": "restaurants",
  "sandwich_shop": "restaurants",
  "sauna": "wellness_beauty",
  "scandinavian_restaurant": "restaurants",
  "scenic_spot": "other",
  "school": "other",
  "school_district": "other",
  "sculpture": "culture_arts",
  "seafood_restaurant": "restaurants",
  "secondary_school": "other",
  "service": "other",
  "shawarma_restaurant": "restaurants",
  "shinto_shrine": "other",
  "shipping_service": "other",
  "shoe_store": "other",
  "shopping_mall": "other",
  "skateboard_park": "experiences",
  "ski_resort": "experiences",
  "skin_care_clinic": "wellness_beauty",
  "snack_bar": "restaurants",
  "soul_food_restaurant": "restaurants",
  "soup_restaurant": "restaurants",
  "south_american_restaurant": "restaurants",
  "south_indian_restaurant": "restaurants",
  "southwestern_us_restaurant": "restaurants",
  "spa": "wellness_beauty",
  "spanish_restaurant": "restaurants",
  "sporting_goods_store": "other",
  "sports_activity_location": "sports_fitness",
  "sports_bar": "bars_nightlife",
  "sports_club": "sports_fitness",
  "sports_coaching": "sports_fitness",
  "sports_complex": "sports_fitness",
  "sports_school": "sports_fitness",
  "sportswear_store": "other",
  "sri_lankan_restaurant": "restaurants",
  "stable": "other",
  "stadium": "experiences",
  "state_park": "experiences",
  "steak_house": "restaurants",
  "storage": "other",
  "store": "other",
  "subway_station": "other",
  "summer_camp_organizer": "other",
  "supermarket": "other",
  "supplier": "other",
  "sushi_restaurant": "restaurants",
  "swimming_pool": "sports_fitness",
  "swiss_restaurant": "restaurants",
  "synagogue": "other",
  "taco_restaurant": "restaurants",
  "tailor": "other",
  "taiwanese_restaurant": "restaurants",
  "tanning_studio": "wellness_beauty",
  "tapas_restaurant": "restaurants",
  "taxi_service": "other",
  "taxi_stand": "other",
  "tea_house": "cafes_bakeries",
  "tea_store": "other",
  "telecommunications_service_provider": "other",
  "television_studio": "other",
  "tennis_court": "sports_fitness",
  "tex_mex_restaurant": "restaurants",
  "thai_restaurant": "restaurants",
  "thrift_store": "other",
  "tibetan_restaurant": "restaurants",
  "tire_shop": "other",
  "toll_station": "other",
  "tonkatsu_restaurant": "restaurants",
  "tour_agency": "other",
  "tourist_attraction": "experiences",
  "tourist_information_center": "other",
  "toy_store": "other",
  "train_station": "other",
  "train_ticket_office": "other",
  "tram_stop": "other",
  "transit_depot": "other",
  "transit_station": "other",
  "transit_stop": "other",
  "transportation_service": "other",
  "travel_agency": "other",
  "truck_dealer": "other",
  "truck_stop": "other",
  "turkish_restaurant": "restaurants",
  "ukrainian_restaurant": "restaurants",
  "university": "other",
  "vegan_restaurant": "restaurants",
  "vegetarian_restaurant": "restaurants",
  "veterinary_care": "other",
  "video_arcade": "experiences",
  "vietnamese_restaurant": "restaurants",
  "vineyard": "experiences",
  "visitor_center": "experiences",
  "warehouse_store": "other",
  "water_park": "experiences",
  "wedding_venue": "experiences",
  "wellness_center": "wellness_beauty",
  "western_restaurant": "restaurants",
  "wholesaler": "other",
  "wildlife_park": "experiences",
  "wildlife_refuge": "experiences",
  "wine_bar": "bars_nightlife",
  "winery": "bars_nightlife",
  "womens_clothing_store": "other",
  "woods": "other",
  "yakiniku_restaurant": "restaurants",
  "yakitori_restaurant": "restaurants",
  "yoga_studio": "sports_fitness",
  "zoo": "experiences",
};

/** Derived from GOOGLE_TYPE_SUPER — one source, no second hand-kept list. */
export const GOOGLE_TYPES_BY_SUPER: Record<SuperOrOther, readonly string[]> = (() => {
  const grouped: Record<SuperOrOther, string[]> = {
    restaurants: [],
    bars_nightlife: [],
    cafes_bakeries: [],
    sports_fitness: [],
    wellness_beauty: [],
    experiences: [],
    culture_arts: [],
    other: [],
  };
  for (const [type, superKey] of Object.entries(GOOGLE_TYPE_SUPER)) {
    grouped[superKey].push(type);
  }
  for (const list of Object.values(grouped)) list.sort();
  return grouped;
})();

const GUEST_SUPERS = new Set<string>([
  "restaurants",
  "bars_nightlife",
  "cafes_bakeries",
  "sports_fitness",
  "wellness_beauty",
  "experiences",
  "culture_arts",
  "undefined",
]);

export function isGuestSuper(value: string): value is GuestSuper {
  return GUEST_SUPERS.has(value);
}

/**
 * One Super (or `other`) for a Google Table A slug.
 * Truncated `*_restaurant` aliases (`fine_dining` → `fine_dining_restaurant`)
 * stay classifiable when a leftover category drops Google's suffix.
 */
export function superForGoogleType(
  primaryType: string | null | undefined,
): SuperOrOther | null {
  if (!primaryType) return null;
  const slug = primaryType.trim().toLowerCase();
  if (!slug) return null;
  const direct = GOOGLE_TYPE_SUPER[slug];
  if (direct) return direct;
  if (!slug.endsWith("_restaurant")) {
    return GOOGLE_TYPE_SUPER[`${slug}_restaurant`] ?? null;
  }
  return null;
}

const NEARBY_TYPE_CAP = 50;
const AUTOCOMPLETE_TYPE_CAP = 5;

/** Nearby `includedPrimaryTypes` — union of Super search batteries, max 50. */
export function nearbyTypesForSupers(
  supers: readonly string[],
): string[] {
  const out: string[] = [];
  const seen = new Set<string>();
  for (const raw of supers) {
    if (!isGuestSuper(raw)) continue;
    for (const t of GOOGLE_SEARCH_TYPES[raw]) {
      if (seen.has(t)) continue;
      seen.add(t);
      out.push(t);
      if (out.length >= NEARBY_TYPE_CAP) return out;
    }
  }
  return out;
}

/** Autocomplete `includedPrimaryTypes` — first 5 of the Nearby union. */
export function autocompleteTypesForSupers(
  supers: readonly string[],
): string[] {
  return nearbyTypesForSupers(supers).slice(0, AUTOCOMPLETE_TYPE_CAP);
}

/** Text Search `includedType` — one slug. First battery of the Super. */
export function textSearchTypeForSuper(superSlug: string): string | null {
  if (!isGuestSuper(superSlug)) return null;
  return GOOGLE_SEARCH_TYPES[superSlug][0] ?? null;
}
