// Regression guard: savePlaceData must accept the payload fetchGoogleBasics
// actually produces.
//
// MESITA-1011 made `places.name` a GENERATED column and dropped `name` from
// the GoogleBasics type — but left savePlaceData validating `place.name`.
// Every create path (admin, business, consumer) 400'd with
// "place.name is required" for 11 days. Nothing caught it:
//   * PlacePayload marks both keys optional, so tsc sees no error;
//   * the `deno check` CI job is non-blocking anyway;
//   * place-name-writes.test.ts scans for name WRITES, not name READS.
//
// So this pins the READ side: the create spine is google_place_id +
// google_name, and a GoogleBasics-shaped payload must reach the inserts.

import { assert, assertEquals } from "jsr:@std/assert@1";
import { savePlaceData } from "./save-place.ts";

// Minimal chainable Supabase stub. select/eq/insert return `this`; the
// terminal maybeSingle/single answer per table. Records the rows written so
// the test can assert what actually lands.
function stubClient(): {
  // deno-lint-ignore no-explicit-any
  admin: any;
  writes: Record<string, Record<string, unknown>>;
} {
  const writes: Record<string, Record<string, unknown>> = {};
  const builder = (table: string) => {
    let pending: Record<string, unknown> | null = null;
    const self = {
      select: () => self,
      eq: () => self,
      delete: () => self,
      insert: (row: Record<string, unknown>) => {
        writes[table] = row;
        pending = row;
        return self;
      },
      maybeSingle: () => {
        // No existing place, no slug collision, no app_config row.
        return Promise.resolve({ data: null, error: null });
      },
      single: () => {
        if (table === "places") {
          return Promise.resolve({ data: { id: "place-uuid-1" }, error: null });
        }
        if (table === "projects") {
          return Promise.resolve({
            data: {
              id: "place-uuid-1",
              slug: (pending?.slug as string) ?? "",
              status: (pending?.status as string) ?? "",
            },
            error: null,
          });
        }
        return Promise.resolve({ data: null, error: null });
      },
    };
    return self;
  };
  return { admin: { from: (t: string) => builder(t) }, writes };
}

// Exactly the shape create-place.ts hands over: fetchGoogleBasics output
// (which deliberately has NO `name`) plus the category seed.
function googleBasicsPayload(): Record<string, unknown> {
  return {
    google_place_id: "ChIJdemo000000000000000",
    google_name: "Cuerno Calzada",
    google_maps_url: "https://maps.google.com/?cid=123",
    lat: 25.6521,
    lng: -100.3617,
    address: "Calz. del Valle 333, Del Valle, 66220 San Pedro Garza García",
    category: "undefined",
    category_label: null,
  };
}

Deno.test("savePlaceData accepts a fetchGoogleBasics payload (no `name` key)", async () => {
  const { admin, writes } = stubClient();
  const payload = googleBasicsPayload();
  assert(!("name" in payload), "fixture must mirror GoogleBasics: no `name`");

  const res = await savePlaceData(admin, payload, "generating");

  assert(
    res.ok,
    `create rejected a real GoogleBasics payload: ${JSON.stringify(
      res.ok ? null : res.body,
    )}`,
  );
  // The Google observation is what persists; `name` is generated by Postgres.
  assertEquals(writes.places.google_name, "Cuerno Calzada");
  assert(!("name" in writes.places), "must never insert the generated `name`");
  assertEquals(
    writes.places.mesita_name,
    "Cuerno Calzada",
    "create seeds mesita_name so profile chrome never reads google_name",
  );
  // Slug and returned label derive from the Google observation, not "".
  assertEquals(writes.projects.slug, "cuerno-calzada");
  assertEquals(res.saved.name, "Cuerno Calzada");
  assertEquals(res.saved.status, "active");
});

Deno.test("savePlaceData still honours the legacy `name` alias", async () => {
  const { admin, writes } = stubClient();
  const { google_name: _drop, ...rest } = googleBasicsPayload();
  const res = await savePlaceData(admin, { ...rest, name: "Cuerno Calzada" }, "generating");

  assert(res.ok, `legacy caller rejected: ${JSON.stringify(res.ok ? null : res.body)}`);
  assertEquals(writes.places.google_name, "Cuerno Calzada");
  assert(!("name" in writes.places), "the legacy alias must land in google_name");
});

Deno.test("savePlaceData rejects a payload with no Google label at all", async () => {
  const { admin } = stubClient();
  const { google_name: _drop, ...rest } = googleBasicsPayload();
  const res = await savePlaceData(admin, rest, "generating");

  assert(!res.ok, "a place with no Google label must not be persisted");
  assertEquals(res.status, 400);
  assertEquals(res.body.error, "place.google_name is required");
});
