// The gate guarding the gate.
//
// sync-shared can only work if CI actually RUNS it, and rules.yml is
// path-filtered: an extension or directory the script owns but the filter
// omits means the workflow never fires, so the check reports green because it
// never ran. YAML cannot import from TypeScript, so this asserts the two stay
// in step — the same trap scripts/sync-rules.test.ts exists for.
import { assert, assertEquals } from "@std/assert";
import { dirname, fromFileUrl, join } from "@std/path";

const repoRoot = dirname(dirname(fromFileUrl(import.meta.url)));
const script = await Deno.readTextFile(join(repoRoot, "scripts", "sync-shared.ts"));
const workflow = await Deno.readTextFile(
  join(repoRoot, ".github", "workflows", "rules.yml"),
);
const denoJson = JSON.parse(
  await Deno.readTextFile(join(repoRoot, "deno.json")),
) as { tasks: Record<string, string> };

/** Every `source:` entry in the script's TARGETS table. */
function sources(): string[] {
  return [...script.matchAll(/^\s*source:\s*"([^"]+)",/gm)].map((m) => m[1]);
}

/** Every `"<app>": "<path>"` pair in the TARGETS table.
 *
 *  DERIVED, NEVER LISTED (MESITA-2037). This used to match
 *  `"(web-admin|web-business)"` — a hardcoded pair, in the one file whose job
 *  is catching a target the gate does not cover. `mock-business-app` became a
 *  target and every assertion below went on passing, because a third app was
 *  invisible to the regex that was supposed to find it. The alternation is
 *  gone: any app key followed by an `src/` path is a target. */
function pairs(): { app: string; rel: string }[] {
  return [...script.matchAll(/"([a-z][a-z0-9-]*)":\s*\n?\s*"(src\/[^"]+)"/g)]
    .map((m) => ({ app: m[1], rel: m[2] }));
}

/** Every destination path in the TARGETS table. */
function destinations(): string[] {
  return pairs().map((p) => p.rel);
}

/** Every app the table writes into, deduped. */
function targetApps(): string[] {
  return [...new Set(pairs().map((p) => p.app))].sort();
}

Deno.test("every canonical source in the manifest exists on disk", async () => {
  const found = sources();
  assert(found.length > 0, "TARGETS must not be empty");
  for (const source of found) {
    const path = join(repoRoot, "shared", source);
    const stat = await Deno.stat(path).catch(() => null);
    assert(stat?.isFile, `missing canonical source: shared/${source}`);
  }
});

Deno.test("every canonical source is hand-edited, never generated", async () => {
  for (const source of sources()) {
    const body = await Deno.readTextFile(join(repoRoot, "shared", source));
    assert(
      !body.startsWith("// GENERATED by scripts/sync-shared.ts"),
      `shared/${source} carries the generated notice; the source is the one ` +
        `file that must not`,
    );
  }
});

Deno.test("every generated copy carries the notice", async () => {
  // PAIRS, NOT A CROSS-PRODUCT (MESITA-2037). This walked every destination
  // path against every app and skipped the misses as "belongs to the other
  // app" — which held only while two apps shared one namespace. The mock is a
  // target now and has its OWN `src/lib/format.ts`, hand-written and not a
  // sync target at all: the cross-product found it, called it a copy, and
  // failed. A pair from TARGETS is the only file this assertion may read.
  const found = pairs();
  assert(found.length > 0, "no destinations parsed — did TARGETS change shape?");
  for (const { app, rel } of found) {
    const path = join(repoRoot, "apps", app, rel);
    const body = await Deno.readTextFile(path).catch(() => null);
    assert(body !== null, `apps/${app}/${rel} is a sync target but is missing`);
    assert(
      body.startsWith("// GENERATED by scripts/sync-shared.ts"),
      `apps/${app}/${rel} is a sync target but carries no notice`,
    );
  }
});

Deno.test("CI runs the check, and the filter lets it fire", () => {
  // The task exists...
  assertEquals(
    denoJson.tasks["sync-shared:check"],
    "deno run --allow-read scripts/sync-shared.ts --check",
  );
  // ...the workflow calls it...
  assert(
    workflow.includes("deno task sync-shared:check"),
    "rules.yml must run sync-shared:check",
  );
  assert(
    workflow.includes("deno task test:shared"),
    "rules.yml must run this test file too",
  );
  // ...and the paths-filter admits the files it guards. `shared/**` covers
  // every canonical source; the app globs cover the generated copies, which is
  // the half that actually drifts when someone edits the wrong file.
  //
  // THE APP GLOBS ARE DERIVED FROM TARGETS (MESITA-2037), so adding a target
  // app the workflow does not watch fails HERE rather than shipping a check
  // that can never fire — the same trap the comment in rules.yml describes.
  const globs = ["shared/**", ...targetApps().map((a) => `apps/${a}/src/**`)];
  for (const glob of globs) {
    assert(
      workflow.includes(`'${glob}'`),
      `rules.yml paths-filter must include ${glob}, or a drifted copy never ` +
        `triggers the check that would catch it`,
    );
  }
});

Deno.test("sync-brand's outputs are not also claimed here", () => {
  // Two owners for one file is a fight, not a guarantee. The brand components
  // and brand-data.ts are generated from assets/brand/brand.json.
  for (const rel of destinations()) {
    assert(
      !rel.includes("components/brand/"),
      `${rel} is generated by sync-brand; it cannot also be a sync-shared target`,
    );
  }
});
