#!/usr/bin/env -S deno run --allow-read --allow-write
// sync-brand.ts — propagate the Mesita brand from ONE canonical source
// (assets/brand/brand.json) into every app that renders it.
//
// CONTRACT (MESITA — brand system v1):
//   assets/brand/brand.json  = SOURCE OF TRUTH. Colour ramp, type, logo geometry,
//                              and the two brand path outlines. Hand-edited.
//   assets/brand/svg/*.svg   = FULLY GENERATED logo assets (currentColor + fixed-fill).
//   assets/brand/tokens.css  = FULLY GENERATED canonical token layer.
//   app globals.css          = generated BRAND-TOKENS block between the markers;
//                              everything outside the markers is the app's own.
//   app components/brand/*   = FULLY GENERATED logo components (web TSX + RN TSX).
//   app public/brand/*.svg   = FULLY GENERATED copies of the canonical assets.
//   mobile tailwind.config   = generated BRAND-TOKENS block between the markers.
//
// Why generate instead of sharing a package: the monorepo has NO root pnpm
// workspace on purpose (mobile needs nodeLinker: hoisted, web apps use the
// default isolated linker), so there is no import path every app can reach.
// Generation is how this repo already keeps CLAUDE.md/AGENTS.md in lockstep —
// see scripts/sync-rules.ts. Same idiom, same --check gate in CI.
//
// Run from the repo root:
//     deno task sync-brand
// Pass --check to verify without writing (STRICT: any drift exits 1).
//
// Worktree conflicts on generated files: regenerate, never hand-merge.

import { dirname, fromFileUrl, join } from "@std/path";

const repoRoot = dirname(dirname(fromFileUrl(import.meta.url)));
const check = Deno.args.includes("--check");

// Same convention as sync-rules.ts: the START marker carries the notice, the
// END marker is bare.
const RUN = "deno task sync-brand";
const CSS_START = `  /* BRAND-TOKENS:START (generated — do not hand-edit; run: ${RUN}) */`;
const CSS_END = "  /* BRAND-TOKENS:END */";
const JS_START = `// BRAND-TOKENS:START (generated — do not hand-edit; run: ${RUN})`;
const JS_END = "// BRAND-TOKENS:END";
const FILE_NOTICE =
  `GENERATED by scripts/sync-brand.ts from assets/brand/brand.json — do not hand-edit. Run: ${RUN}`;

// ── source of truth ────────────────────────────────────────────────────────
type Swatch = { oklch: string; hex: string; onWhite: number };
type Brand = {
  name: string;
  wordmark: string;
  color: {
    hue: number;
    pink: Record<string, Swatch>;
    role: Record<string, { ref?: string; oklch?: string; hex?: string; use: string }>;
    gradient: Record<
      "pink" | "brand",
      {
        angle: string;
        stops: string[];
        stopsHex?: string[];
        from?: string;
        to?: string;
        use: string;
        note: string;
      }
    >;
  };
  type: Record<string, { family: string; css: string; use: string; tracking?: string }>;
  art: {
    mark: { viewBox: string; ink: { w: number; h: number; x: number[]; y: number[] }; centroid: { x: number; y: number }; opticalCenterPct: number; d: string };
    wordmark: { ink: { w: number; h: number; x: number[]; y: number[] }; baseline: number; xHeight: Record<string, number>; aspect: number; d: string };
    lockup: Record<"stacked" | "horizontal", { viewBox: string; markTransform: string; wordmarkTransform: string; gap?: number }>;
    clearSpace: number;
    minSize: Record<string, number>;
  };
  targets: { web: string[]; mobile: string[] };
};

const brand: Brand = JSON.parse(
  await Deno.readTextFile(join(repoRoot, "assets", "brand", "brand.json")),
);

const PINK = brand.color.pink["500"].hex;
const INK = brand.color.role["brand-ink"].hex!;
const { mark, wordmark, lockup } = brand.art;

/**
 * A CSS gradient, line-broken exactly the way prettier formats it, so running
 * `pnpm format` can never put a generated block out of sync with this script.
 */
function gradientCss(key: "pink" | "brand"): string {
  const g = brand.color.gradient[key];
  return `linear-gradient(\n    ${[g.angle, ...g.stops].join(",\n    ")}\n  )`;
}

/** width / height of a "0 0 W H" viewBox. */
function aspectOf(viewBox: string): number {
  const [, , w, h] = viewBox.split(/\s+/).map(Number);
  return w / h;
}

// ── writer ─────────────────────────────────────────────────────────────────
let updated = 0, drifted = 0, failed = 0;

async function write(relPath: string, next: string): Promise<void> {
  const path = join(repoRoot, relPath);
  let current: string | null;
  try {
    current = await Deno.readTextFile(path);
  } catch {
    current = null;
  }
  if (current === next) return;
  drifted++;
  if (check) {
    console.error(`OUT OF SYNC: ${relPath}`);
    return;
  }
  await Deno.mkdir(dirname(path), { recursive: true });
  await Deno.writeTextFile(path, next);
  updated++;
  console.log(`updated: ${relPath}`);
}

/** Replace the region between markers, leaving the rest of the file alone. */
async function writeBlock(
  relPath: string,
  start: string,
  end: string,
  body: string,
): Promise<void> {
  const path = join(repoRoot, relPath);
  let text: string;
  try {
    text = await Deno.readTextFile(path);
  } catch {
    console.error(`MISSING: ${relPath}`);
    failed++;
    return;
  }
  const s = text.indexOf(start);
  const e = text.indexOf(end);
  if (s === -1 || e === -1 || s > e) {
    console.error(
      `BAD MARKERS in ${relPath} — expected:\n  ${start}\n  …\n  ${end}`,
    );
    failed++;
    return;
  }
  const next = text.slice(0, s) + `${start}\n${body}\n${end}` + text.slice(e + end.length);
  await write(relPath, next);
}

// ── 1. logo assets ─────────────────────────────────────────────────────────
// Every asset is emitted twice: a `currentColor` version (what components and
// inline use want) and fixed-fill colour/black/white versions (what design
// tools, email, and slide decks want).

const svg = (viewBox: string, body: string, fill: string, title: string) =>
  `<!-- ${FILE_NOTICE} -->\n` +
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" fill="${fill}" role="img" aria-label="${title}">\n` +
  `${body}\n</svg>\n`;

const markBody = (indent = "  ") => `${indent}<path d="${mark.d}"/>`;
// The wordmark outlines live in their own coordinate space; normalise to a
// height-100 box so the asset is composable without magic numbers downstream.
const WORDMARK_SCALE = 100 / wordmark.ink.h;
const WORDMARK_VIEWBOX = `0 0 ${(wordmark.ink.w * WORDMARK_SCALE).toFixed(2)} 100`;
const wordmarkBody = (indent = "  ") =>
  `${indent}<g transform="scale(${WORDMARK_SCALE.toFixed(6)}) translate(${-wordmark.ink.x[0]} ${-wordmark.ink.y[0]})">\n` +
  `${indent}  <path d="${wordmark.d}"/>\n${indent}</g>`;

const lockupBody = (kind: "stacked" | "horizontal", indent = "  ") =>
  `${indent}<g transform="${lockup[kind].markTransform}">\n` +
  `${indent}  <path d="${mark.d}"/>\n${indent}</g>\n` +
  `${indent}<g transform="${lockup[kind].wordmarkTransform}">\n` +
  `${indent}  <path d="${wordmark.d}"/>\n${indent}</g>`;

const ASSETS: { name: string; viewBox: string; body: string; title: string }[] = [
  { name: "mark", viewBox: mark.viewBox, body: markBody(), title: "Mesita" },
  { name: "wordmark", viewBox: WORDMARK_VIEWBOX, body: wordmarkBody(), title: "mesita." },
  { name: "logo-horizontal", viewBox: lockup.horizontal.viewBox, body: lockupBody("horizontal"), title: "Mesita" },
  { name: "logo-stacked", viewBox: lockup.stacked.viewBox, body: lockupBody("stacked"), title: "Mesita" },
];

const FILLS: [string, string][] = [
  ["", "currentColor"],
  ["-color", PINK],
  ["-black", INK],
  ["-white", "#ffffff"],
];

for (const a of ASSETS) {
  for (const [suffix, fill] of FILLS) {
    await write(`assets/brand/svg/${a.name}${suffix}.svg`, svg(a.viewBox, a.body, fill, a.title));
  }
}

// Full-colour mark on the brand pink, for avatars / app tiles / OG images.
await write(
  "assets/brand/svg/mark-badge.svg",
  `<!-- ${FILE_NOTICE} -->\n` +
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" role="img" aria-label="Mesita">\n` +
    `  <rect width="100" height="100" rx="22" fill="${PINK}"/>\n` +
    `  <g transform="translate(50 50) scale(0.62) translate(-50 -50)" fill="#ffffff">\n` +
    `    <path d="${mark.d}"/>\n  </g>\n</svg>\n`,
);

// ── 2. canonical token layer ───────────────────────────────────────────────
const rampCss = Object.entries(brand.color.pink)
  .map(([step, s]) => `  --brand-pink-${step}: ${s.oklch}; /* ${s.hex} · ${s.onWhite}:1 on white */`)
  .join("\n");

const tokensCss =
  `/* ${FILE_NOTICE} */\n\n` +
  `/* The Mesita brand layer. Every app imports these values through its own\n` +
  `   globals.css BRAND-TOKENS block — this file is the readable original.\n\n` +
  `   Contrast notes are measured, not guessed:\n` +
  `   · --brand-pink (500) is ${brand.color.pink["500"].onWhite}:1 on white — AA for LARGE text only.\n` +
  `     White-on-pink buttons must be >=16px semibold. For pink text at body\n` +
  `     size on white use --brand-pink-text (600, ${brand.color.pink["600"].onWhite}:1).\n` +
  `   · Every ramp step is inside the sRGB gamut, so the same pink renders on\n` +
  `     sRGB and P3 displays. Do not raise chroma without re-checking. */\n\n` +
  `:root {\n${rampCss}\n\n` +
  Object.entries(brand.color.role)
    .map(([k, v]) => {
      const val = v.ref ? `var(--brand-${v.ref.replace(".", "-")})` : v.oklch;
      return `  /* ${v.use} */\n  --${k}: ${val};`;
    })
    .join("\n") +
  `\n\n  /* ${brand.color.gradient.pink.note} */\n` +
  `  --gradient-pink: ${gradientCss("pink")};\n` +
  `  /* ${brand.color.gradient.brand.use}\n     ${brand.color.gradient.brand.note} */\n` +
  `  --gradient-brand: ${gradientCss("brand")};\n\n` +
  `  --font-display: ${brand.type.display.family}, Georgia, serif;\n` +
  `  --font-body: ${brand.type.body.family}, system-ui, sans-serif;\n` +
  `  --tracking-display: ${brand.type.display.tracking};\n}\n`;

await write("assets/brand/tokens.css", tokensCss);

// ── 3. per-app CSS token block ─────────────────────────────────────────────
// Only the BRAND layer is generated. Each app keeps its own semantic tokens
// (surfaces, tier colours, app-specific gradients) outside the markers.
const appTokenBlock =
  `  /* --- Mesita brand · generated from assets/brand/brand.json --- */\n` +
  rampCss +
  `\n\n  /* THE Mesita pink. Logo fill, primary buttons, active states. */\n` +
  `  --brand-pink: var(--brand-pink-500);\n` +
  `  /* Pink text at body size on white — clears AA (${brand.color.pink["600"].onWhite}:1). --brand-pink does NOT (${brand.color.pink["500"].onWhite}:1). */\n` +
  `  --brand-pink-text: var(--brand-pink-600);\n` +
  `  /* Pressed states, pink on tinted surfaces. */\n` +
  `  --brand-pink-deep: var(--brand-pink-700);\n\n` +
  `  /* Both endpoints were outside sRGB and silently clipped by the browser,\n` +
  `     so the ramp rendered differently per display. Snapped to the in-gamut\n` +
  `     chroma ceiling at each lightness. */\n` +
  `  --gradient-pink: ${gradientCss("pink")};\n\n` +
  `  /* ${brand.color.gradient.brand.use}\n` +
  `     Renamed from --gradient-peacock (a pre-pivot bird name on a pink\n` +
  `     gradient); its first stop was also clipping out of sRGB. */\n` +
  `  --gradient-brand: ${gradientCss("brand")};`;

for (const app of brand.targets.web) {
  await writeBlock(
    `apps/${app}/src/app/globals.css`,
    CSS_START,
    CSS_END,
    appTokenBlock,
  );
}

// ── 4. web logo components ─────────────────────────────────────────────────
const webComponents = (): Record<string, string> => ({
  "brand-data.ts":
    `// ${FILE_NOTICE}\n` +
    `//\n` +
    `// The brand as data, for surfaces that need to DISPLAY it (the /brand\n` +
    `// reference page) rather than just use it. Contrast ratios are measured\n` +
    `// against #ffffff, not estimated.\n` +
    `export const BRAND_PINK_RAMP = [\n` +
    Object.entries(brand.color.pink)
      .map(
        ([step, s]) =>
          `  { step: ${step}, oklch: "${s.oklch}", hex: "${s.hex}", onWhite: ${s.onWhite} },`,
      )
      .join("\n") +
    `\n] as const;\n\n` +
    `export const BRAND_ROLES = [\n` +
    Object.entries(brand.color.role)
      .map(
        ([name, v]) =>
          `  {\n    token: "--${name}",\n    ref: ${v.ref ? `"${v.ref}"` : "null"},\n    use: ${JSON.stringify(v.use)},\n  },`,
      )
      .join("\n") +
    `\n] as const;\n\n` +
    `export const BRAND_GEOMETRY = {\n` +
    `  clearSpace: ${brand.art.clearSpace},\n` +
    // Always multi-line: adding a key must never push this past 80 columns and
    // put the generated file out of step with prettier.
    `  minSize: {\n${
      Object.entries(brand.art.minSize).map(([k, v]) => `    ${k}: ${v},`).join("\n")
    }\n  },\n` +
    `  markOpticalCenterPct: ${mark.opticalCenterPct},\n` +
    `} as const;\n\n` +
    `export const BRAND_TYPE = {\n` +
    Object.entries(brand.type)
      .map(
        ([role, t]) =>
          `  ${role}: {\n    family: "${t.family}",\n    use: ${JSON.stringify(t.use)},\n  },`,
      )
      .join("\n") +
    `\n} as const;\n`,

  "MesitaMark.tsx":
    `// ${FILE_NOTICE}\n` +
    `//\n` +
    `// The Mesita flame. Inlined rather than <img src="/brand/mark.svg"> so it\n` +
    `// inherits text colour and costs no request. Pure JSX — safe in server and\n` +
    `// client components alike.\n` +
    `//\n` +
    `// \`strokeWidth\` is accepted and ignored: the bottom nav renders every tab\n` +
    `// glyph through one lucide-shaped signature, and Home uses this mark. The\n` +
    `// flame is a filled shape, so the prop has no visual effect.\n` +
    `export function MesitaMark({\n` +
    `  className,\n` +
    `}: {\n` +
    `  className?: string;\n` +
    `  strokeWidth?: number;\n` +
    `}) {\n` +
    `  return (\n` +
    `    <svg\n` +
    `      viewBox="${mark.viewBox}"\n` +
    `      fill="currentColor"\n` +
    `      role="img"\n` +
    `      aria-hidden\n` +
    `      className={className}\n` +
    `    >\n` +
    `      <path d="${mark.d}" />\n` +
    `    </svg>\n` +
    `  );\n` +
    `}\n`,

  "MesitaWordmark.tsx":
    `// ${FILE_NOTICE}\n` +
    `//\n` +
    `// The "mesita." wordmark as outlines, not live text — the logo must not\n` +
    `// reflow if Fraunces fails to load or a user overrides fonts.\n` +
    `export function MesitaWordmark({ className }: { className?: string }) {\n` +
    `  return (\n` +
    `    <svg\n` +
    `      viewBox="${WORDMARK_VIEWBOX}"\n` +
    `      fill="currentColor"\n` +
    `      role="img"\n` +
    `      aria-hidden\n` +
    `      className={className}\n` +
    `    >\n` +
    `      <g transform="scale(${WORDMARK_SCALE.toFixed(6)}) translate(${-wordmark.ink.x[0]} ${-wordmark.ink.y[0]})">\n` +
    `        <path d="${wordmark.d}" />\n` +
    `      </g>\n` +
    `    </svg>\n` +
    `  );\n` +
    `}\n`,

  "MesitaLogo.tsx":
    `// ${FILE_NOTICE}\n` +
    `//\n` +
    `// The full Mesita lockup — mark + wordmark, drawn as one SVG so the\n` +
    `// proportions between them can never drift.\n` +
    `//\n` +
    `//   "horizontal"  mark beside wordmark. Headers, nav bars, email. The\n` +
    `//                 wordmark's x-height band is centred on the mark's AREA\n` +
    `//                 centroid (${mark.centroid.y} in a 100-unit mark), because the\n` +
    `//                 flame is bottom-heavy and box-centring reads low.\n` +
    `//   "stacked"     mark above wordmark. Splash, auth, share cards, print.\n` +
    `//\n` +
    `// Colour comes from \`currentColor\`. On a light surface use the brand pink\n` +
    `// (\`text-primary\`); on pink or photography use \`text-white\`. Size it by\n` +
    `// setting a height — the viewBox carries the aspect ratio.\n` +
    `//\n` +
    `// Minimum sizes: horizontal ${brand.art.minSize.horizontalPx}px wide, stacked ${brand.art.minSize.stackedPx}px, bare mark ${brand.art.minSize.markPx}px.\n` +
    `// Keep ${brand.art.clearSpace}x the mark's width clear on every side.\n` +
    `const LOCKUP = {\n` +
    `  horizontal: {\n` +
    `    viewBox: "${lockup.horizontal.viewBox}",\n` +
    `    mark: "${lockup.horizontal.markTransform}",\n` +
    `    wordmark: "${lockup.horizontal.wordmarkTransform}",\n` +
    `  },\n` +
    `  stacked: {\n` +
    `    viewBox: "${lockup.stacked.viewBox}",\n` +
    `    mark: "${lockup.stacked.markTransform}",\n` +
    `    wordmark: "${lockup.stacked.wordmarkTransform}",\n` +
    `  },\n` +
    `} as const;\n\n` +
    `export function MesitaLogo({\n` +
    `  variant = "horizontal",\n` +
    `  className,\n` +
    `  title = "Mesita",\n` +
    `}: {\n` +
    `  variant?: "horizontal" | "stacked";\n` +
    `  className?: string;\n` +
    `  /** Pass \`null\` when adjacent text already names the brand. */\n` +
    `  title?: string | null;\n` +
    `}) {\n` +
    `  const art = LOCKUP[variant];\n` +
    `  return (\n` +
    `    <svg\n` +
    `      viewBox={art.viewBox}\n` +
    `      fill="currentColor"\n` +
    `      className={className}\n` +
    `      role={title ? "img" : undefined}\n` +
    `      aria-label={title ?? undefined}\n` +
    `      aria-hidden={title ? undefined : true}\n` +
    `    >\n` +
    `      <g transform={art.mark}>\n` +
    `        <path d="${mark.d}" />\n` +
    `      </g>\n` +
    `      <g transform={art.wordmark}>\n` +
    `        <path d="${wordmark.d}" />\n` +
    `      </g>\n` +
    `    </svg>\n` +
    `  );\n` +
    `}\n`,
});

for (const app of brand.targets.web) {
  for (const [file, source] of Object.entries(webComponents())) {
    await write(`apps/${app}/src/components/brand/${file}`, source);
  }
  // public copies for OG images, <img> tags, and anything outside React
  for (const a of ASSETS) {
    for (const [suffix, fill] of FILLS.slice(1)) {
      await write(
        `apps/${app}/public/brand/${a.name}${suffix}.svg`,
        svg(a.viewBox, a.body, fill, a.title),
      );
    }
  }
  // favicon — the bare mark, sized to fill the tab square with a little air
  await write(
    `apps/${app}/src/app/icon.svg`,
    `<!-- ${FILE_NOTICE} -->\n` +
      `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" role="img" aria-label="Mesita">\n` +
      `  <g transform="translate(50 50) scale(1.18) translate(-50 -50)" fill="${PINK}">\n` +
      `    <path d="${mark.d}"/>\n  </g>\n</svg>\n`,
  );
}

// ── 5. mobile ──────────────────────────────────────────────────────────────
const mobileTokenBlock =
  Object.entries(brand.color.pink)
    .map(([step, s]) => `        'brand-pink-${step}': '${s.hex}',`)
    .join("\n") +
  `\n        // THE Mesita pink (== web --primary / --brand-pink-500).\n` +
  `        'brand-pink': '${PINK}',\n` +
  `        // Pink text at body size — clears AA (${brand.color.pink["600"].onWhite}:1). brand-pink does NOT (${brand.color.pink["500"].onWhite}:1).\n` +
  `        'brand-pink-text': '${brand.color.pink["600"].hex}',\n` +
  `        'brand-pink-deep': '${brand.color.pink["700"].hex}',`;

const mobileConstantsBlock =
  `export const BRAND_PINK = '${PINK}';\n` +
  `/** Pink text at body size on white — clears AA (${brand.color.pink["600"].onWhite}:1). BRAND_PINK does NOT (${brand.color.pink["500"].onWhite}:1). */\n` +
  `export const BRAND_PINK_TEXT = '${brand.color.pink["600"].hex}';\n` +
  `export const BRAND_PINK_DEEP = '${brand.color.pink["700"].hex}';\n` +
  `/** ${brand.color.gradient.pink.note} */\n` +
  `export const BRAND_GRADIENT_PINK = ['${brand.color.gradient.pink.from}', '${brand.color.gradient.pink.to}'] as const;\n` +
  `/** ${brand.color.gradient.brand.use} ${brand.color.gradient.brand.note} */\n` +
  `export const BRAND_GRADIENT = [${brand.color.gradient.brand.stopsHex!.map((c) => `'${c}'`).join(", ")}] as const;\n` +
  `export const BRAND_PINK_RAMP = {\n` +
  Object.entries(brand.color.pink).map(([step, s]) => `  ${step}: '${s.hex}',`).join("\n") +
  `\n} as const;`;

const rnComponents = (): Record<string, string> => ({
  "MesitaMark.tsx":
    `// ${FILE_NOTICE}\n` +
    `//\n` +
    `// RN port of the web MesitaMark. Web tints via currentColor; RN has no such\n` +
    `// thing, so colour is an explicit prop. \`strokeWidth\` is accepted and\n` +
    `// ignored for lucide-shaped call sites in the tab bar.\n` +
    `import { Platform } from 'react-native';\n` +
    `import Svg, { Path } from 'react-native-svg';\n\n` +
    `// Decorative — keep it out of the a11y tree. Native uses RN's a11y props;\n` +
    `// on web react-native-svg forwards those to the DOM and React warns, so use\n` +
    `// aria-hidden there instead. (MESITA-571)\n` +
    `const hiddenFromA11y = Platform.select({\n` +
    `  web: { 'aria-hidden': true },\n` +
    `  default: {\n` +
    `    accessibilityElementsHidden: true,\n` +
    `    importantForAccessibility: 'no-hide-descendants',\n` +
    `  },\n` +
    `});\n\n` +
    `export function MesitaMark({\n` +
    `  color = '${PINK}',\n` +
    `  size = 24,\n` +
    `  strokeWidth: _strokeWidth,\n` +
    `}: {\n` +
    `  color?: string;\n` +
    `  size?: number;\n` +
    `  strokeWidth?: number;\n` +
    `}) {\n` +
    `  return (\n` +
    `    <Svg\n` +
    `      width={size}\n` +
    `      height={size}\n` +
    `      viewBox="${mark.viewBox}"\n` +
    `      {...(hiddenFromA11y as object)}\n` +
    `    >\n` +
    `      <Path fill={color} d="${mark.d}" />\n` +
    `    </Svg>\n` +
    `  );\n` +
    `}\n`,

  "MesitaLogo.tsx":
    `// ${FILE_NOTICE}\n` +
    `//\n` +
    `// RN port of the web MesitaLogo — same geometry, same two variants, so the\n` +
    `// native apps and the web apps cannot drift apart. Size by width; height\n` +
    `// follows the lockup's aspect ratio.\n` +
    `import Svg, { G, Path } from 'react-native-svg';\n\n` +
    `const LOCKUP = {\n` +
    `  horizontal: {\n` +
    `    viewBox: '${lockup.horizontal.viewBox}',\n` +
    `    aspect: ${aspectOf(lockup.horizontal.viewBox).toFixed(4)},\n` +
    `    mark: '${lockup.horizontal.markTransform}',\n` +
    `    wordmark: '${lockup.horizontal.wordmarkTransform}',\n` +
    `  },\n` +
    `  stacked: {\n` +
    `    viewBox: '${lockup.stacked.viewBox}',\n` +
    `    aspect: ${aspectOf(lockup.stacked.viewBox).toFixed(4)},\n` +
    `    mark: '${lockup.stacked.markTransform}',\n` +
    `    wordmark: '${lockup.stacked.wordmarkTransform}',\n` +
    `  },\n` +
    `} as const;\n\n` +
    `export function MesitaLogo({\n` +
    `  variant = 'horizontal',\n` +
    `  width = 160,\n` +
    `  color = '${PINK}',\n` +
    `}: {\n` +
    `  variant?: 'horizontal' | 'stacked';\n` +
    `  width?: number;\n` +
    `  color?: string;\n` +
    `}) {\n` +
    `  const art = LOCKUP[variant];\n` +
    `  return (\n` +
    `    <Svg\n` +
    `      width={width}\n` +
    `      height={width / art.aspect}\n` +
    `      viewBox={art.viewBox}\n` +
    `      aria-hidden\n` +
    `    >\n` +
    `      <G transform={art.mark}>\n` +
    `        <Path fill={color} d="${mark.d}" />\n` +
    `      </G>\n` +
    `      <G transform={art.wordmark}>\n` +
    `        <Path fill={color} d="${wordmark.d}" />\n` +
    `      </G>\n` +
    `    </Svg>\n` +
    `  );\n` +
    `}\n`,
});

for (const app of brand.targets.mobile) {
  await writeBlock(
    `apps/${app}/tailwind.config.js`,
    `        ${JS_START}`,
    `        ${JS_END}`,
    mobileTokenBlock,
  );
  await writeBlock(
    `apps/${app}/src/constants/brand.ts`,
    JS_START,
    JS_END,
    mobileConstantsBlock,
  );
  for (const [file, source] of Object.entries(rnComponents())) {
    await write(`apps/${app}/src/components/brand/${file}`, source);
  }
}

console.log(`\nsync-brand: ${updated} updated, ${drifted} drifted, ${failed} failed.`);
if (failed > 0 || (check && drifted > 0)) {
  console.error(
    check
      ? "\nBrand assets are out of sync with assets/brand/brand.json. Run: deno task sync-brand"
      : "",
  );
  Deno.exit(1);
}
