// The gate guarding the gate.
//
// sync-shared can only work if CI actually RUNS it, and rules.yml is
// path-filtered: an extension or directory the script owns but the filter
// omits means the workflow never fires, so the check reports green because it
// never ran. YAML cannot import from TypeScript, so this asserts the two stay
// in step — the same trap scripts/sync-rules.test.ts exists for.
import { assert, assertEquals } from "@std/assert";
import { dirname, fromFileUrl, join } from "@std/path";

const repoRoot = dirname(dirname(fromFileUrl(import.meta.url)));
const script = await Deno.readTextFile(join(repoRoot, "scripts", "sync-shared.ts"));
const workflow = await Deno.readTextFile(
  join(repoRoot, ".github", "workflows", "rules.yml"),
);
const denoJson = JSON.parse(
  await Deno.readTextFile(join(repoRoot, "deno.json")),
) as { tasks: Record<string, string> };

/** Every `source:` entry in the script's TARGETS table. */
function sources(): string[] {
  return [...script.matchAll(/^\s*source:\s*"([^"]+)",/gm)].map((m) => m[1]);
}

/** Every destination path in the TARGETS table. */
function destinations(): string[] {
  return [...script.matchAll(/"(web-admin|web-business)":\s*\n?\s*"([^"]+)"/g)]
    .map((m) => m[2]);
}

Deno.test("every canonical source in the manifest exists on disk", async () => {
  const found = sources();
  assert(found.length > 0, "TARGETS must not be empty");
  for (const source of found) {
    const path = join(repoRoot, "shared", source);
    const stat = await Deno.stat(path).catch(() => null);
    assert(stat?.isFile, `missing canonical source: shared/${source}`);
  }
});

Deno.test("every canonical source is hand-edited, never generated", async () => {
  for (const source of sources()) {
    const body = await Deno.readTextFile(join(repoRoot, "shared", source));
    assert(
      !body.startsWith("// GENERATED by scripts/sync-shared.ts"),
      `shared/${source} carries the generated notice; the source is the one ` +
        `file that must not`,
    );
  }
});

Deno.test("every generated copy carries the notice", async () => {
  const dests = destinations();
  assert(dests.length > 0, "no destinations parsed — did TARGETS change shape?");
  for (const rel of dests) {
    for (const app of ["web-admin", "web-business"]) {
      const path = join(repoRoot, "apps", app, rel);
      const body = await Deno.readTextFile(path).catch(() => null);
      if (body === null) continue; // this rel belongs to the other app
      assert(
        body.startsWith("// GENERATED by scripts/sync-shared.ts"),
        `apps/${app}/${rel} is a sync target but carries no notice`,
      );
    }
  }
});

Deno.test("CI runs the check, and the filter lets it fire", () => {
  // The task exists...
  assertEquals(
    denoJson.tasks["sync-shared:check"],
    "deno run --allow-read scripts/sync-shared.ts --check",
  );
  // ...the workflow calls it...
  assert(
    workflow.includes("deno task sync-shared:check"),
    "rules.yml must run sync-shared:check",
  );
  assert(
    workflow.includes("deno task test:shared"),
    "rules.yml must run this test file too",
  );
  // ...and the paths-filter admits the files it guards. `shared/**` covers
  // every canonical source; the app globs cover the generated copies, which is
  // the half that actually drifts when someone edits the wrong file.
  for (const glob of ["shared/**", "apps/web-admin/src/**", "apps/web-business/src/**"]) {
    assert(
      workflow.includes(`'${glob}'`),
      `rules.yml paths-filter must include ${glob}, or a drifted copy never ` +
        `triggers the check that would catch it`,
    );
  }
});

Deno.test("sync-brand's outputs are not also claimed here", () => {
  // Two owners for one file is a fight, not a guarantee. The brand components
  // and brand-data.ts are generated from assets/brand/brand.json.
  for (const rel of destinations()) {
    assert(
      !rel.includes("components/brand/"),
      `${rel} is generated by sync-brand; it cannot also be a sync-shared target`,
    );
  }
});
