// GENERATED by scripts/sync-shared.ts from shared/state-vocabulary.ts — do not
// hand-edit. Edit the source and run: deno task sync-shared
// State — two boxes (Pato, 2026-08-25 · 2026-08-29).
//
//   STATES (12)   Created · Active · Listed · Enriching · Enriched ·
//                 Verified · Owned · Partnered · Mesita Pay · Mesita Credits
//                 are bools (`true` / `false`). Requested is the guest request
//                 count, 0…n — not a Yes/No. Visit Rewards (wire key
//                 `promoting`, formerly labeled Promoted) is 0 | 1 | 2. Never a
//                 places.state. Mesita Pay / Mesita Credits are per-place
//                 acceptance intent bits (place_profiles.mesita_pay_enabled /
//                 place_profiles.credits_enabled) — operator toggles on the Partner tab
//                 (the set-place-rails doors); engines still gate each rail.
//
//                 OWNED joined the box with MESITA-1608: an organization holds
//                 this place. It is CONSTANT on either console list — Org
//                 Places filters on it and the pool filters on its absence —
//                 and Pato kept it anyway, so both screens render one column
//                 set and the fact goes live the day an unfiltered list
//                 exists. It is not Verified: holding an address and having
//                 PROVED you hold it are different claims.
//   INTAKE (11)   own box: 0. Seed … 10. Embedding, each a bool: called or not
//
// Repeating the row name on the chip is redundant. Enriching is the live run;
// Enriched is last-completed — they are independent. Intake just names the
// eleven functions. Create 1–5 / Enrich 1–10 stay Config sequences; they are
// not a third State ladder. Wire key `seeded` stays; the label is Created.
// Function 10 was renamed `semantic` → `embedding` (§8.4); stored blobs and
// event payloads may still say `semantic` — readers fold, never rewrite.

export type StateBoolChip = "true" | "false" | "?" | "…";

/** Chip for a binary State fact. Loading and unknown stay distinct. */
export function stateBoolChip(
  value: boolean | "unknown" | "loading" | null | undefined,
): StateBoolChip {
  if (value === "loading") return "…";
  if (value === "unknown" || value == null) return "?";
  return value ? "true" : "false";
}

/**
 * Operator Visit Rewards: 0 Zero · 1 Conservative · 2 Aggressive.
 * Engine Dominant (3) displays as 2 — the picker has three strategies.
 */
export function operatorPromotingLevel(
  raw: number | null | undefined,
): 0 | 1 | 2 {
  const n = typeof raw === "number" && Number.isFinite(raw) ? Math.trunc(raw) : 0;
  if (n <= 0) return 0;
  if (n === 1) return 1;
  return 2;
}

export function promotingLevelChip(
  raw: number | null | undefined,
): "0" | "1" | "2" {
  return String(operatorPromotingLevel(raw)) as "0" | "1" | "2";
}

/** Guest request count. Missing is "?"; the State fact is the number. */
export function requestCountFromRow(
  requestCount: unknown,
): number | "unknown" {
  if (requestCount == null || requestCount === "") return "unknown";
  const n = Number(requestCount);
  if (!Number.isFinite(n) || n < 0) return "unknown";
  return Math.trunc(n);
}

/** Chip for Requested: `0` · `1` · `12` · … or `?`. Never true/false. */
export function requestCountChip(requestCount: unknown): string {
  const n = requestCountFromRow(requestCount);
  return n === "unknown" ? "?" : String(n);
}

export const OPERATOR_PROMOTING_LABEL: Record<0 | 1 | 2, string> = {
  0: "Zero",
  1: "Conservative",
  2: "Aggressive",
};

/** Live strategy → operator 0|1|2. Dominant and custom rates display as 2. */
export function promotingLevelFromStrategy(
  live: boolean,
  strategy: string | null | undefined,
): 0 | 1 | 2 {
  if (!live) return 0;
  if (strategy === "conservative") return 1;
  return 2;
}

export const GENERAL_STATE_FACTS = [
  { key: "seeded", label: "Created" },
  { key: "active", label: "Active" },
  { key: "listed", label: "Listed" },
  { key: "requested", label: "Requested" },
  { key: "enriching", label: "Enriching" },
  { key: "enriched", label: "Enriched" },
  { key: "verified", label: "Verified" },
  { key: "owned", label: "Owned" },
  { key: "partner", label: "Partnered" },
  { key: "promoting", label: "Visit Rewards" },
  { key: "mesita_pay", label: "Mesita Pay" },
  { key: "credits", label: "Mesita Credits" },
] as const;

export type GeneralStateKey = (typeof GENERAL_STATE_FACTS)[number]["key"];

/** EMPTY (Pato, 2026-09-08, decision: overturns MESITA-1608's "a free place
 *  and a place that doesn't take a not-yet-live rail are not defects"):
 *  "small ui details make them same color style, like red-green not gray"
 *  — Partner/Mesita Pay/Credits/Owned used to render grey when false; every
 *  general-state false reads rose now, no exceptions. Kept as a live map,
 *  not deleted, because the shape (StateCell's `falseTone` prop, the
 *  `?? "pending"` fallback at both call sites) is unchanged — only which
 *  keys populate it did. */
export const STATE_FACT_FALSE_TONE: Partial<Record<GeneralStateKey, "neutral">> = {};

/** Acceptance bits with NO engine yet (decision: Pato gate 2026-08-29).
 *  They now have a writer (the Capabilities tab toggles, the set-place-rails doors)
 *  and a reader (the Promotion score), but the rails themselves stay staged —
 *  header chips, Global Monitor filter segments and notification meta chips
 *  OMIT these until the Mesita Pay gateway / Credits PRs lift the
 *  filters; the catalog table and the State box still show them. */
export const ENGINELESS_STATE_FACT_KEYS: readonly GeneralStateKey[] = [
  "mesita_pay",
  "credits",
];

/**
 * Facts the NOTIFICATION stamper does not write (MESITA-1608).
 *
 * The admin notifications door puts a stateFacts blob on each item, and
 * the feed reads facts straight out of it. Owned is not in that blob: it is a
 * join fact (`places.organization_id`), not something an enrichment event
 * observes, and nothing stamps it.
 *
 * Which is why this list exists rather than a `?? false` at the read site.
 * Defaulting an unwritten fact to false would have made every notification in
 * the feed claim "no organization holds this place" — a statement nobody
 * checked, on a surface whose whole job is reporting what happened. The key
 * leaves the feed's type instead, so indexing it is a compile error rather
 * than a plausible-looking lie.
 *
 * Different question from ENGINELESS above: those facts ARE stamped and
 * merely have no engine driving them yet.
 */
export const UNSTAMPED_STATE_FACT_KEYS = ["owned"] as const;

/** A general fact the notification payload actually carries. */
export type StampedStateFactKey = Exclude<
  GeneralStateKey,
  (typeof UNSTAMPED_STATE_FACT_KEYS)[number]
>;

export const INTAKE_FUNCTIONS = [
  { key: "seed", label: "Seed", n: 0 },
  { key: "pulse", label: "Pulse", n: 1 },
  { key: "details", label: "Details", n: 2 },
  { key: "serp", label: "Serp", n: 3 },
  { key: "links", label: "Links", n: 4 },
  { key: "social", label: "Social", n: 5 },
  { key: "images", label: "Images", n: 6 },
  { key: "menu", label: "Menu", n: 7 },
  { key: "reviews", label: "Reviews", n: 8 },
  { key: "description", label: "Description", n: 9 },
  { key: "embedding", label: "Embedding", n: 10 },
] as const;

export type IntakeFunctionKey = (typeof INTAKE_FUNCTIONS)[number]["key"];

export const GENERAL_STATE_COUNT = GENERAL_STATE_FACTS.length;
export const INTAKE_FUNCTION_COUNT = INTAKE_FUNCTIONS.length;

/** Operator label: `0. Seed` … `10. Embedding`. */
export function intakeFunctionLabel(n: number, label: string): string {
  return `${n}. ${label}`;
}

// ── Capabilities — what a guest can DO here (Notion Main §11.2) ────────────
//
// A SECOND LIST, NOT A SPLIT. `GENERAL_STATE_FACTS` above stays exactly as it
// is, twelve facts, because thirteen files across shared/, web-admin and
// web-business read its keys — `STATE_FACT_FALSE_TONE`,
// `ENGINELESS_STATE_FACT_KEYS`, `StampedStateFactKey`'s `Exclude<>`, both
// notification feeds, `PlaceStatesTable`'s `SortKey`. Splitting it to move
// three capability-shaped facts out is a ~30-file change across four packages
// that no user can see. Adding this list beside it closes the fork that DOES
// matter — the Capabilities tab hand-typing its own labels — in eight.
//
// Deduping the two is a separate issue and needs a naming decision first.
//
// WHO WRITES THE FACT is the field that earns its place. It is what predicts
// every bug this screen has shipped: Reservations read `off` for months on a
// hard-coded constant while the consumer app booked guests off the same
// column, because an OBSERVED fact was sitting in a DECLARED-shaped row. A
// row renders its control from `writer`, so "why is there no switch here" is
// answered by the data instead of by a comment.
//
//   declared       an operator asked for it (a rail toggle)
//   observed       the Intaker inferred it from the listing
//   administrative Mesita sets it (plan, strategy)
//   external       a third party decides (Stripe)
//
// `column` is the `place_profiles` column a toggle writes, or null when
// nothing writes it. NULL COLUMN ⇒ NO SWITCH: `_shared/place-rails.ts`
// silently skips a key its `RAIL_COLUMNS` does not know, so a switch for a
// column-less capability returns 200 and writes nothing. The bijection test
// pins this in both directions.
//
// `spec` is the Main §11.2 number, or null for a capability that is real in
// the schema but absent from the spec. Recording the mismatch here is the
// point: §11.2 also lists "Visits Enabled" (no column anywhere — and
// `business-web-list-places/payload.test.ts` fences it as "the draft
// taxonomy's inventions"), and splits Delivery into First- and Third-Party
// when Main §2.3.7 strikes First-Party through and §8 files Third-Party under
// Future Expansions. Those three are a Notion correction, not a migration.

export type CapabilityWriter =
  | "declared"
  | "observed"
  | "administrative"
  | "external";

export const PLACE_CAPABILITIES = [
  {
    key: "mesita_pay",
    label: "Mesita Pay",
    detail: "Guests pay the bill by card, inside Mesita.",
    writer: "declared",
    column: "mesita_pay_enabled",
    spec: 1,
  },
  {
    key: "visit_rewards",
    label: "Visits Rewards",
    detail: "What a visit pays back — Zero, Conservative or Aggressive.",
    writer: "administrative",
    column: null,
    spec: 3,
  },
  {
    key: "credits",
    label: "Accept Prepays",
    detail: "Redeem a guest's prepaid balance as a bill discount, never a payment.",
    writer: "declared",
    column: "credits_enabled",
    spec: null,
  },
  {
    key: "pickup",
    label: "Pickup Orders",
    detail: "Guests order ahead and pick up.",
    writer: "declared",
    column: "pickup_orders_enabled",
    spec: 4,
  },
  {
    key: "delivery",
    label: "Delivery Orders",
    detail: "Guests order for delivery, on the place's own fleet.",
    writer: "declared",
    column: "delivery_orders_enabled",
    spec: 5,
  },
  {
    key: "reservations",
    label: "Reservations",
    detail: "Guests book a table.",
    writer: "observed",
    column: "reservations_enabled",
    spec: 7,
  },
] as const;

export type PlaceCapabilityKey = (typeof PLACE_CAPABILITIES)[number]["key"];

export const PLACE_CAPABILITY_COUNT = PLACE_CAPABILITIES.length;

/** The `place_profiles` column a capability's toggle writes, or null when
 *  nothing writes it. A null column MUST render without a switch. */
export function capabilityColumn(key: PlaceCapabilityKey): string | null {
  return PLACE_CAPABILITIES.find((c) => c.key === key)?.column ?? null;
}

/** What the control column says when a capability is not the operator's to
 *  set. Never "Soon" — a ship date is something an operator can neither act
 *  on nor verify, and this tab's own ladder already argues that a prerequisite
 *  beats a date. Name the actor instead. */
export const CAPABILITY_WRITER_WORD: Record<CapabilityWriter, string> = {
  declared: "",
  observed: "Observed",
  administrative: "Set by Mesita",
  external: "Set by Stripe",
};
