import type { PlaceFieldPermission } from "./place-field-permissions";

export const PLACE_FIELD_PERMISSIONS: PlaceFieldPermission[] = [
  // ── Google native — seeded at create, re-stamped on every enrich ────────
  {
    key: "name",
    label: "Name",
    group: "Google native",
    note: "Every enrich re-copies the Google name over manual corrections.",
    native: true,
    enricher: false,
    admin: true,
    business: true,
  },
  {
    key: "hours",
    label: "Hours",
    group: "Google native",
    note: "A correction holds only until the next enrich.",
    native: true,
    enricher: false,
    admin: true,
    business: true,
  },
  {
    key: "google_maps_url",
    label: "Google Maps",
    group: "Google native",
    note: "Derived from the Google place id at create; EF rejects every manual write. Create without a Google Place ID is invalid.",
    native: true,
    enricher: false,
    admin: false,
    business: false,
  },
  {
    key: "price_level",
    label: "Price",
    group: "Google native",
    note: "Google Places only — the EF rejects manual writes.",
    native: true,
    enricher: false,
    admin: false,
    business: false,
  },
  {
    key: "address",
    label: "Address",
    group: "Google native",
    note: "EF rejects manual writes.",
    native: true,
    enricher: false,
    admin: false,
    business: false,
  },
  {
    key: "lat_lng",
    label: "Lat / Lng",
    group: "Google native",
    native: true,
    enricher: false,
    admin: false,
    business: false,
  },
  {
    key: "zone_city",
    label: "Zone / City",
    group: "Google native",
    note: "City stays exactly as Google seeded it; only the zone is refined.",
    native: true,
    enricher: true,
    admin: false,
    business: false,
  },
  {
    key: "timezone",
    label: "Timezone",
    group: "Google native",
    note: "Shown read-only beside hours.",
    native: true,
    enricher: false,
    admin: false,
    business: false,
  },

  // ── Enriched — pipeline inference, Mesita may correct ───────────────────
  {
    key: "category",
    label: "Category",
    group: "Enriched",
    note: "The seed lands ‘undefined’; the slug is inferred from the catalog.",
    native: false,
    enricher: true,
    admin: true,
    business: true,
  },
  {
    key: "tags",
    label: "Tags",
    group: "Enriched",
    note: "Picked from the Atlas catalog, max 20 per place.",
    native: false,
    enricher: true,
    admin: true,
    business: true,
  },
  {
    key: "description",
    label: "Description",
    group: "Enriched",
    note: "The About block on the place profile.",
    native: false,
    enricher: true,
    admin: true,
    business: true,
  },
  {
    key: "photos",
    label: "Photos",
    group: "Enriched",
    note: "Google seeds them at create; the vision funnel re-ranks them.",
    native: false,
    enricher: true,
    admin: true,
    business: true,
  },
  {
    key: "phone",
    label: "Phone",
    group: "Enriched",
    note: "Enricher research stage may seed from Google; contents stage never overwrites contacts.",
    native: false,
    enricher: true,
    admin: true,
    business: true,
  },
  {
    key: "website_url",
    label: "Website",
    group: "Enriched",
    native: false,
    enricher: true,
    admin: true,
    business: true,
  },
  {
    key: "instagram_url",
    label: "Instagram",
    group: "Enriched",
    note: "Enricher discovery + identity judge (lenient fallback). Changing the account re-runs the Apify follower scrape.",
    native: false,
    enricher: true,
    admin: true,
    business: true,
  },
  {
    key: "facebook_url",
    label: "Facebook",
    group: "Enriched",
    note: "Changing the page re-runs the Apify follower/rating scrape.",
    native: false,
    enricher: true,
    admin: true,
    business: true,
  },
  {
    key: "opentable_url",
    label: "OpenTable",
    group: "Enriched",
    native: false,
    enricher: true,
    admin: true,
    business: true,
  },
  {
    key: "uber_eats_url",
    label: "Uber Eats",
    group: "Enriched",
    native: false,
    enricher: true,
    admin: true,
    business: true,
  },
  {
    key: "reservations",
    label: "Reservations",
    group: "Enriched",
    note: "Enricher selects a channel (phone / WhatsApp / Instagram) into products.reservations; an admin selector pick wins and re-enrich never clobbers it.",
    native: false,
    enricher: true,
    admin: true,
    business: true,
  },
  {
    key: "profile_details",
    label: "Profile details",
    group: "Enriched",
    note: "Editorial summary, established year, executive chef + details JSON — synthesis-only, no manual edit surface.",
    native: false,
    enricher: true,
    admin: false,
    business: false,
  },

  // ── Manual — Mesita input only, never enriched ──────────────────────────
  {
    key: "email",
    label: "Email",
    group: "Manual",
    native: false,
    enricher: false,
    admin: true,
    business: true,
  },
  {
    key: "whatsapp_url",
    label: "WhatsApp",
    group: "Manual",
    note: "Not in the Enricher discovery set — phone-shaped Mesita input.",
    native: false,
    enricher: false,
    admin: true,
    business: true,
  },
  {
    key: "menu_pdf_url",
    label: "Menu URL",
    group: "Manual",
    note: "URL + display name, in the business Place editor.",
    native: false,
    enricher: false,
    admin: false,
    business: true,
  },
  {
    key: "secondary_urls",
    label: "X / Threads / Reddit / Resy / DiDi Food",
    group: "Manual",
    note: "Secondary channels — accepted by the EF whitelist, hidden in both Place UIs today.",
    native: false,
    enricher: false,
    admin: false,
    business: true,
  },

  // ── Signals — machine-written metrics, read-only everywhere ─────────────
  {
    key: "google_stars_overall",
    label: "Google rating",
    group: "Signals",
    note: "Refreshed on every enrich.",
    native: true,
    enricher: false,
    admin: false,
    business: false,
  },
  {
    key: "google_review_count",
    label: "Google review count",
    group: "Signals",
    native: true,
    enricher: false,
    admin: false,
    business: false,
  },
  {
    key: "google_reviews",
    label: "Google reviews",
    group: "Signals",
    note: "Apify Google Maps scrape, capped at 100 reviews per run.",
    native: false,
    enricher: true,
    admin: false,
    business: false,
  },
  {
    key: "popular_times",
    label: "Popular times",
    group: "Signals",
    note: "Written during enrich when the gathered material supports it.",
    native: false,
    enricher: true,
    admin: false,
    business: false,
  },
  {
    key: "instagram_followers_count",
    label: "Instagram followers",
    group: "Signals",
    note: "Indirect only — follows the Instagram account; Apify refreshes on account change. Never typed.",
    native: false,
    enricher: true,
    admin: false,
    business: false,
  },
  {
    key: "facebook_followers",
    label: "Facebook followers",
    group: "Signals",
    note: "Indirect only — follows the Facebook page; Apify refreshes on account change. Never typed.",
    native: false,
    enricher: true,
    admin: false,
    business: false,
  },
  {
    key: "facebook_rating",
    label: "Facebook rating",
    group: "Signals",
    note: "Apify page scrape alongside followers.",
    native: false,
    enricher: true,
    admin: false,
    business: false,
  },
  {
    key: "mesita_ratings",
    label: "Mesita ratings",
    group: "Signals",
    note: "Consumer review aggregates (stars + counts) — columns reserved, no writer wired yet.",
    native: false,
    enricher: false,
    admin: false,
    business: false,
  },

  // ── Lifecycle — row state + billing, not profile content ────────────────
  {
    key: "status",
    label: "Status",
    group: "Lifecycle",
    note: "active / paused / archived — set via the EF; the admin Meta card only displays it.",
    native: false,
    enricher: false,
    admin: false,
    business: true,
  },
  {
    key: "content_status",
    label: "Enrichment status",
    group: "Lifecycle",
    note: "queued → generating → ready / failed — pipeline-owned lifecycle flag.",
    native: false,
    enricher: true,
    admin: false,
    business: false,
  },
  {
    key: "plan",
    label: "Plan",
    group: "Lifecycle",
    note: "Billing, not profile — the EF rejects it; changes only through the Stripe subscription flow.",
    native: false,
    enricher: false,
    admin: false,
    business: false,
  },
];
